# 1 Flowchart
### Write a function Print_values with arguments a, b, and c to reflect the following flowchart. Here the purple parallelogram operator on a list [x, y, z] is to compute and print x+y-10z. Try your output with some random a, b, and c values. Report your output when a = 10, b = 5, c = 1.

In [5]:
def Print_values(a,b,c):
    if a>b:
        if b>c:
            print(a,b,c)
        else:
            if a>c:
                print(a,c,b)
            else:
                print(c,a,b)
    else:
        if b>c:
            pass
        else:
            print(c,b,a)
    print("x+y-10z="+str(a+b-10*c))
Print_values(10,5,1)


10 5 1
x+y-10z=5


### 2.Given a list with N positive integers. For every element x of the list, find the value of continuous ceiling function defined as F(x) = F(ceil(x/3)) + 2x, where F(1) = 1

In [3]:
#以下是用递归方法写的函数
import math
def ceil_function(n):
    if n==1:
        return 1
    return ceil_function(math.ceil(n/3))+2*n
# 输入数字
str_integer=input("please input a positive interger x to calculate F(X):")
int_integer=int(str_integer) 
ceil_function(int_integer)


please input a positive interger x to calculate F(X):20


61

# 3.Dice rolling
##  Given 10 dice each with 6 faces, numbered from 1 to 6. Write a function Find_number_of_ways to find the number of ways to get sum x, defined as the sum of values on each face when all the dice are thrown.

In [49]:
count=10
def Find_number_of_ways(count,x):
    m=10**9 + 7
    if x<0:
        return 0
    if count==1 & x<=6:
        return 1
    if count<=0:
        return 0
    else:
        return (Find_number_of_ways(count-1,x-1)+Find_number_of_ways(count-1,x-2)+Find_number_of_ways(count-1,x-3)+Find_number_of_ways(count-1,x-4)+Find_number_of_ways(count-1,x-5)+Find_number_of_ways(count-1,x-6))%m
# 下面是验证    
Find_number_of_ways(10,60)

20155392

#  Count the number of ways for any x from 10 to 60, assign the number of ways to a list called Number_of_ways, so which x yields the maximum of Number_of_ways?

In [35]:
ways=[]
for i in range(10,20):
    ways.append(Find_number_of_ways(10,i))
print(ways)

[1, 10, 55, 221, 724, 2049, 5179, 11937, 25450, 50716]


### 4.1  Write a function Random_integer to fill an array of N elements by randomly selecting integers from 0 to 10

In [3]:
#这是函数
import random
import numpy as np
def random_integers(n):
    random_list=np.random.randint(0,10,n)
    return random_list
#以下用来测试
print(random_integers(10))
print(random_integers(9))


[0 0 1 0 6 9 0 4 4 7]
[9 7 3 5 5 5 8 6 6]


### 4.2  Write a function Sum_averages to compute the sum of the average of all subsets of the array. For example, given an array of [1, 2, 3], you Sum_averages function should compute the sum of: average of [1], average of [2], average of [3], average of [1, 2], average of [1, 3], average of [2, 3], and average of [1, 2, 3].

In [12]:
import numpy
def sum_average(arr):
    finish=[]    # the list containing all the subsequences of the specified sequence
    size = len(arr)    # the number of elements in the specified sequence
    end = 1 << size    # end=2**size
    for index in range(end):   
        array = []    # remember to clear the list before each loop
        for j in range(size):
            if (index >> j) % 2:    # this result is 1, so do not have to write ==
                array.append(arr[j])
        # print(array)
        finish.append(numpy.mean(array))  
    del finish[0]
    return sum(finish)
# 测试
sum_average(random_integers(6))

304.50000000000006

>上述方法参考引用了https://blog.csdn.net/Tiffany_959/article/details/102651770
*使用其生成的子列求得平均值，再调用sum函数相加

## 4.3 [5 points] Call Sum_averages with N increasing from 1 to 100, assign the output to a list called Total_sum_averages. Plot Total_sum_averages, describe what do you see

In [17]:
total_sum_average=[]
for i in range(1,10):
    total_sum_average.append(sum_average(random_integers(i)))
    print("this is "+str(i))
print(total_sum_average)
%time

this is 1
this is 2
this is 3
this is 4
this is 5
this is 6
this is 7
this is 8
this is 9
[7.0, 12.0, 46.666666666666664, 41.25, 173.6, 314.99999999999994, 435.42857142857116, 828.7500000000003, 2668.5555555555543]
CPU times: total: 0 ns
Wall time: 0 ns


*这种方法似乎无法支持较大的n值，算法的复杂程度高*

## 5.1 [5 points] Create a matrix with N rows and M columns, fill the right-bottom corner and top-left corner cells with 1, and randomly fill the rest of matrix with integer 0 or 1.

In [62]:
import numpy as np
def matrix_a(N,M):
  
    m=int(M)
    n=int(N)
    arr=np.random.randint(2,size=(n,m))
    arr[0,0]=1
    arr[n-1,m-1]=1
    return arr
# 以下是测试结果
matrix_a(10,8)


array([[1, 1, 0, 0, 0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1, 0, 1, 1],
       [0, 1, 0, 0, 1, 1, 1, 0, 1],
       [0, 1, 1, 1, 0, 1, 0, 0, 1],
       [1, 1, 0, 1, 0, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 1, 0, 1, 1]])

# 5.2 [25 points] Consider a cell marked with 0 as a blockage or dead-end, and a cell marked with 1 is good to go. Write a function Count_path to count total number of paths to reach the right-bottom corner cell from the top-left corner cell.

In [160]:
def Count_path(n,m):
    cell=matrix_a(n,m)
    solution=np.zeros((n,m))
    solution[0,0]=1
    
    # 填充结果中第一列
    for i in range(0,n):
        if cell[0,i]==0:
            solution[i,0]=0

        else:
            solution[i][0]=1
    # 填充结果中第一行
    for j in range(0,m):
        if cell[0,j]==0:
            solution[0,j]=0

        else: 
            solution[0,j]=1
    #进行路径的选择
    for x in range(1,n):
        for y in range(1,m):
            if cell[x,y]==0:
                solution[x,y]=0
            else:
                solution[x,y]=solution[x-1,y]+solution[x,y-1]
    return solution[n-1,m-1]
            
Count_path(6,7)        


0.0

# 5.3 [5 points] Let N = 10, M = 8, run Count_path for 1000 times, each time the matrix (except the right-bottom corner and top-left corner cells, which remain being 1) is re-filled with integer 0 or 1 randomly, report the mean of total number of paths from the 1000 runs.


In [163]:
arr2=[]
for i in range(1001):
    arr2.append(Count_path(6,10))
print(np.mean(arr2))

0.9600399600399601
